export const data =[
    {
     id:"100",
        name:"Siva",
        batch:"B43Wd",
        email:"siva@gmail.com",
        experience:5,
    },
    {
        id:"101",
           name:"Selva",
           batch:"B43Wd",
           email:"selva@gmail.com",
           experience:3,
       },
       {
        id:"102",
           name:"Karthik",
           batch:"B43Wd",
           email:"Karthik@gmail.com",
           experience:2,
       },
       {
            id:"103",
           name:"Kumar",
           batch:"B43Wd",
           email:"Kumar@gmail.com",
           experience:1,
       }
   
];